### ISSUE TITLE
AssertionError : len(self.keypoints_3d_pred) != len(self)

### ISSUE THREAD

**Issue by rakesh-menon** [karfly/learnable-triangulation-pytorch#37]
Hi,

I followed the instructions for downloading the dataset as mentioned [here](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/datasets/human36m_preprocessing/README.md). But even after following these instructions, I end up with an assertion error at [this line](https://github.com/karfly/learnable-triangulation-pytorch/blob/dfa76a03e9e619e69e72c585bfd9fe31d9b81853/mvn/datasets/human36m.py#L109). I downloaded the validations results from the google drive link mentioned (file size 5.6M for results_val.pkl; train works fine). Is this because of some error in the validation file link? 

Thanks!

**Comment by shrubb** [comment]
This is a notorious problem, happens when you have a different number of images in the dataset from what we had. You're not the first one to face it, so I think we're going to refactor this section entirely, hopefully today.

**Comment by karfly** [comment]
Hi, @rakesh-menon.

Such problem appears, because in our experiments we use full Human3.6M test-set (all frames) and we published precalculated results for all frames. [This repository](https://github.com/anibali/h36m-fetch) extracts not all, but some of the frames, and that's why you got size mismatch.

In  #42 I uploaded new precalculated results which should work with preprocessing pipeline from [this repository](https://github.com/anibali/h36m-fetch). Please, update them and tell if it helped you.

**Comment by shrubb** [comment]
@rakesh-menon
It seems like #42 has provided a quick fix by changing that Google drive file (now it is aligned with our Human3.6M preprocessing instructions). Everything should work now, so I decided to leave the code as is.

Thanks for reporting!
