### ISSUE TITLE
How to generate these diagrams in your paper and save detected results of the 3D human skeleton?

### ISSUE THREAD

**Issue by BenoitKAO** [karfly/learnable-triangulation-pytorch#39]
How to generate these diagrams in your paper and save detected results of the 3D human skeleton?
https://reurl.cc/Zn8RNp
https://reurl.cc/A1XE9j
https://reurl.cc/RdRK2Z
https://reurl.cc/5gX7XM

Could you please give some video streaming examples for inputs as OpenPose that can generate output files in format?
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md

Thank you.

**Comment by junhao1999** [comment]
> How to generate these diagrams in your paper and save detected results of the 3D human skeleton?
> https://reurl.cc/Zn8RNp
> https://reurl.cc/A1XE9j
> https://reurl.cc/RdRK2Z
> https://reurl.cc/5gX7XM
> 
> Could you please give some video streaming examples for inputs as OpenPose that can generate output files in format?
> https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
> 
> Thank you.

It would be great if video streaming examples could be provided

**Comment by BenoitKAO** [comment]
Surely, this is the video streaming which is often demoed by OpenPose:

Crazy Uptown Funk flashmob in Sydney
https://www.youtube.com/watch?v=2DiQUX11YaY

Thank you.

**Comment by karfly** [comment]
Hi, @BenoitKAO and @junhao1999.

1. All plots of 3D skeletons are drawn with [this function](https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/utils/vis.py#L355).

2. We're not planning to release a streaming demo. It's quite a difficult engineering task to implement a general multi-camera imaging pipeline, which will be common for all camera setups, due to variety of camera brands and SDKs. E.g. OpenPose supports multi-camera 3D human pose estimation only for FLIR cameras.

**Comment by BenoitKAO** [comment]
Thank you for your replay.

Could you give examples on how to use draw_3d_pose method to plot?

**Comment by karfly** [comment]
```python3
from matplotlib import pylab as plt
from mpl_toolkits.mplot3d import axes3d, Axes3D

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

vis.draw_3d_pose(keypoints_3d, ax, kind='coco')
```
