### ISSUE TITLE
about camera parameters for wild test

### ISSUE THREAD

**Issue by TonyFaith** [karfly/learnable-triangulation-pytorch#40]
thanks for this wonderful work! 

i want to predict 3d results by human_alg_model with my own data and camera parameters, but there is something wrong with the camera parameters for Camera function in [https://github.com/karfly/learnable-triangulation-pytorch/blob/master/mvn/utils/multiview.py]  sef.K.dot(self.extrinsics) line. The error shows that "shapes (3,3) and (143,6,1) not aligned: 3 (dim 1) != 6 (dim 1) " 

my camera parameters' shape for 3 camera is, top camera: K: (3,3) R:(143,3,1),t:(143,3,1),dist:(1,5). right camera: K: (3,3) R:(139,3,1),t:(139,3,1),dist:(1,5). left camera: K: (3,3) R:(147,3,1),t:(147,3,1),dist:(1,5).

would you please show the right camera parameters shape needed here?

**Comment by shrubb** [comment]
```python3
R.shape == (3, 3)
t.shape == (3, 1)
K.shape == (3, 3)
```

Let me improve the code to reflect this.

**Comment by TonyFaith** [comment]
@shrubb  thanks a lot shrubb. I am  a little confused with the camera parameters for R,t. How is it compute for human36m datasets（does it have word coordinate set ?）, should i follow his way to get R, t in my datasets?

**Comment by shrubb** [comment]
In our code, there is a central [`Camera` class](https://github.com/karfly/learnable-triangulation-pytorch/blob/4fa83d2913d7fd03a98c433c7db20075c2aeffc6/mvn/utils/multiview.py#L5). It is used to project 3D points into images using camera parameters. Therefore, it defines the [corresponding formulae](https://github.com/karfly/learnable-triangulation-pytorch/blob/4fa83d2913d7fd03a98c433c7db20075c2aeffc6/mvn/utils/multiview.py#L80), which are probably what you are interested in. I suggest that you adapt your `R`, `t`, `K` so that they suit those formulae.

**Comment by TonyFaith** [comment]
@shrubb  thanks! 
i have read the corresponding formulation you suggested but i am still confused about R,t,k parameters, is that changed between frame? K,dist is intrinsics camera parameters, right? why it is changed? R , t is changed each frame?  how can i calibrate my camera to get the right R,t,K?? thanks for your attention.

**Comment by shrubb** [comment]
> R,t,k parameters, is that changed between frame?
> why it is changed? R , t is changed each frame?
If you crop images to the bounding boxes of humans, then yes. Otherwise, no.

> K,dist is intrinsics camera parameters, right?
Yes.

> how can i calibrate my camera to get the right R,t,K?? thanks for your attention.
Many ways to do this you can google up. For example, OpenCV library's `calib3d` module does this.
