### ISSUE TITLE
CMU hand keypoints dataset using learnable triangulation

### ISSUE THREAD

**Issue by pablovela5620** [karfly/learnable-triangulation-pytorch#61]
I wanted to use the algebraic and volumetric triangulation methods on the hand keypoint portion of the cmu dataset. I had a couple of questions about how this would work

1. Why do you use mask-rcnn to get bounding boxes rather than deriving them from the dataset keypoints
2. Hands have a tendency to be completely occluded form certain views, would this mean that rather than just using 4 cameras to train the alg/vol networks more cameras should be used?
3. Should visibility be taken into account as CMU includes that in the data? What is the difference between visibility and validity?

**Comment by yurymalkov** [comment]
Hi @pablovela5620 
1. Because it is closer to the real evaluation. During runtime you do not actually know the keypoints to infer the rectangle. 
2. AFAIK more than 4 cameras were used during the training, but I cannot see how it is connected to occlusions. 
3. Visibility is just some flag from CMU specific to a view and does not affect the accuracy of gt and therefore, not needed. Validity is the actual data on which keypoints were triangulated successfully (and therefore we can trust), it does not depend on the view.
